import type { Component } from 'svelte';

export type PanelLoader = () => Promise<{ default: Component }>;

export const PANEL_MAP: Record<string, PanelLoader> = {
  'navigator:files': () => import('@/hubs/navigator/components/FileTreePanel.svelte'),
  'navigator:open-editors': () => import('@/hubs/navigator/components/OpenEditorsPanel.svelte'),
  'navigator:search': () => import('@/hubs/navigator/components/SearchPanel.svelte'),
  'navigator:recent': () => import('@/hubs/navigator/components/RecentPanel.svelte'),
  'navigator:bookmarks': () => import('@/hubs/navigator/components/BookmarksPanel.svelte'),
  'navigator:templates': () => import('@/hubs/navigator/components/TemplatePanel.svelte'),
  'navigator:capture': () => import('@/hubs/navigator/components/CapturePanel.svelte'),
  'planner:calendar': () => import('@/hubs/planner/components/CalendarPanel.svelte'),
  'planner:tasks': () => import('@/hubs/planner/components/TasksPanel.svelte'),
  'planner:daily': () => import('@/hubs/planner/components/DailyNotePanel.svelte'),
  'planner:periodic': () => import('@/hubs/planner/components/PeriodicPanel.svelte'),
  'planner:habits': () => import('@/hubs/planner/components/HabitsPanel.svelte'),
  'knowledge:tags': () => import('@/hubs/knowledge/components/TagsPanel.svelte'),
  'knowledge:vault-stats': () => import('@/hubs/knowledge/components/VaultStatsPanel.svelte'),
  'knowledge:citations': () => import('@/hubs/knowledge/components/CitationsPanel.svelte'),
  'knowledge:connections': () => import('@/hubs/knowledge/components/ConnectionsPanel.svelte'),
  'knowledge:portent': () => import('@/hubs/knowledge/components/PortentPanel.svelte'),
  'knowledge:topic-links': () => import('@/hubs/knowledge/components/TopicLinkPanel.svelte'),
  'editor:outline': () => import('@/hubs/editor/components/OutlinePanel.svelte'),
  'editor:properties': () => import('@/hubs/editor/components/PropertiesPanel.svelte'),
  'editor:backlinks': () => import('@/hubs/editor/components/BacklinksPanel.svelte'),
  'editor:outgoing': () => import('@/hubs/editor/components/OutgoingLinksPanel.svelte'),
  'editor:versions': () => import('@/hubs/integration/components/VersionHistoryPanel.svelte'),
  'editor:wordcount': () => import('@/hubs/editor/components/WordCountPanel.svelte'),
  'editor:footnotes': () => import('@/hubs/editor/components/FootnotesPanel.svelte'),
  'editor:symbols': () => import('@/hubs/editor/components/SymbolsPanel.svelte'),
  'canvas:inspector': () => import('@/hubs/canvas/components/CanvasInspector.svelte'),
  'canvas:layers': () => import('@/hubs/canvas/components/LayersPanel.svelte'),
  'canvas:elements': () => import('@/hubs/canvas/components/ElementsPanel.svelte'),
  'creative:ideas': () => import('@/hubs/creative/components/IdeasPanel.svelte'),
  'creative:writing': () => import('@/hubs/creative/components/WritingPanel.svelte'),
  'media:browser': () => import('@/hubs/media/components/MediaBrowserPanel.svelte'),
  'media:attachments': () => import('@/hubs/media/components/AttachmentsPanel.svelte'),
  'media:embeds': () => import('@/hubs/media/components/EmbedPanel.svelte'),
  'integration:git': () => import('@/hubs/integration/components/GitPanel.svelte'),
  'integration:ai': () => import('@/hubs/integration/components/AiPanel.svelte'),
  'integration:backup': () => import('@/hubs/integration/components/BackupPanel.svelte'),
  'integration:publish': () => import('@/hubs/integration/components/PublishPanel.svelte'),
  'integration:rss': () => import('@/hubs/integration/components/RssPanel.svelte'),
  'editor:lint': () => import('@/hubs/editor/components/LintPanel.svelte'),
  'editor:speedreader': () => import('@/hubs/editor/components/SpeedReaderPanel.svelte'),
  'graph:local-graph': () => import('@/hubs/knowledge/components/GraphPanel.svelte'),
  'graph:graph-config': () => import('@/hubs/knowledge/components/GraphConfigPanel.svelte'),
};
