import type { ComponentDefinition } from '@/features/canvas/types';

const now = 0;

function btn(
  id: string,
  name: string,
  icon: string,
  w: number,
  h: number,
  fillColor: string,
  textColor: string,
  stroke?: string
): ComponentDefinition {
  const labelY = Math.round((h - 16) / 2);
  const elements: ComponentDefinition['elements'] = [
    {
      id: 'bg',
      element_type: 'rectangle',
      x: 0,
      y: 0,
      width: w,
      height: h,
      rotation: 0,
      properties: { fill: fillColor, ...(stroke ? { stroke, strokeWidth: 1 } : {}), radius: 6 },
      layer_id: 'default',
      z_index: 0,
      locked: false,
      visible: true,
      name: 'Background',
    },
    {
      id: 'label',
      element_type: 'text',
      x: 12,
      y: labelY,
      width: w - 24,
      height: 16,
      rotation: 0,
      properties: {
        text: name,
        fontSize: 13,
        fontWeight: 500,
        fill: textColor,
        textAlign: 'center',
      },
      layer_id: 'default',
      z_index: 1,
      locked: false,
      visible: true,
      name: 'Label',
    },
  ];
  return {
    id,
    name,
    category: 'Buttons',
    icon,
    elements,
    exposedProps: [{ key: 'label', label: 'Label', type: 'text', defaultValue: name }],
    width: w,
    height: h,
    tags: ['button', 'action', 'interactive'],
    isBuiltin: true,
    created_at: now,
    modified_at: now,
  };
}

function iconBtn(id: string, name: string, iconName: string, size: number): ComponentDefinition {
  const offset = Math.round((size - 16) / 2);
  return {
    id,
    name,
    category: 'Buttons',
    icon: iconName,
    elements: [
      {
        id: 'bg',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: size,
        height: size,
        rotation: 0,
        properties: {
          fill: 'var(--background-primary)',
          stroke: 'var(--border-color)',
          strokeWidth: 1,
          radius: 6,
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Background',
      },
      {
        id: 'icon',
        element_type: 'text',
        x: offset,
        y: offset,
        width: 16,
        height: 16,
        rotation: 0,
        properties: {
          text: iconName,
          fontSize: 11,
          fontWeight: 400,
          fill: 'var(--text-muted)',
          textAlign: 'center',
        },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Icon',
      },
    ],
    exposedProps: [{ key: 'icon', label: 'Icon', type: 'text', defaultValue: iconName }],
    width: size,
    height: size,
    tags: ['button', 'icon', 'action'],
    isBuiltin: true,
    created_at: now,
    modified_at: now,
  };
}

export const BUTTON_COMPONENTS: ComponentDefinition[] = [
  btn(
    'builtin-btn-primary-sm',
    'Primary (sm)',
    'square',
    88,
    32,
    'var(--interactive-accent)',
    'var(--text-on-accent)'
  ),
  btn(
    'builtin-btn-primary',
    'Primary',
    'square',
    120,
    40,
    'var(--interactive-accent)',
    'var(--text-on-accent)'
  ),
  btn(
    'builtin-btn-primary-lg',
    'Primary (lg)',
    'square',
    152,
    48,
    'var(--interactive-accent)',
    'var(--text-on-accent)'
  ),
  btn(
    'builtin-btn-secondary-sm',
    'Secondary (sm)',
    'square',
    88,
    32,
    'var(--background-primary)',
    'var(--text-normal)',
    'var(--border-color)'
  ),
  btn(
    'builtin-btn-secondary',
    'Secondary',
    'square',
    120,
    40,
    'var(--background-primary)',
    'var(--text-normal)',
    'var(--border-color)'
  ),
  btn(
    'builtin-btn-secondary-lg',
    'Secondary (lg)',
    'square',
    152,
    48,
    'var(--background-primary)',
    'var(--text-normal)',
    'var(--border-color)'
  ),
  btn('builtin-btn-ghost', 'Ghost', 'square', 120, 40, 'transparent', 'var(--interactive-accent)'),
  btn(
    'builtin-btn-destruct',
    'Destructive',
    'alert-triangle',
    120,
    40,
    'var(--color-danger, #dc2626)',
    '#ffffff'
  ),
  btn(
    'builtin-btn-destruct-ghost',
    'Destructive Ghost',
    'alert-triangle',
    120,
    40,
    'transparent',
    'var(--color-danger, #dc2626)'
  ),
  iconBtn('builtin-btn-icon-sm', 'Icon Btn (sm)', 'plus', 28),
  iconBtn('builtin-btn-icon', 'Icon Button', 'plus', 36),
  iconBtn('builtin-btn-icon-lg', 'Icon Btn (lg)', 'plus', 44),
  {
    id: 'builtin-btn-toolbar',
    name: 'Toolbar Button',
    category: 'Buttons',
    icon: 'layout',
    elements: [
      {
        id: 'bg',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 32,
        height: 32,
        rotation: 0,
        properties: { fill: 'transparent', radius: 4 },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Background',
      },
      {
        id: 'icon',
        element_type: 'text',
        x: 7,
        y: 7,
        width: 18,
        height: 18,
        rotation: 0,
        properties: { text: 'icon', fontSize: 10, fill: 'var(--text-muted)', textAlign: 'center' },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Icon',
      },
    ],
    exposedProps: [{ key: 'icon', label: 'Icon', type: 'text', defaultValue: 'icon' }],
    width: 32,
    height: 32,
    tags: ['button', 'toolbar', 'compact'],
    isBuiltin: true,
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-btn-toolbar-active',
    name: 'Toolbar Button (active)',
    category: 'Buttons',
    icon: 'layout',
    elements: [
      {
        id: 'bg',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 32,
        height: 32,
        rotation: 0,
        properties: { fill: 'var(--background-modifier-hover)', radius: 4 },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Background',
      },
      {
        id: 'icon',
        element_type: 'text',
        x: 7,
        y: 7,
        width: 18,
        height: 18,
        rotation: 0,
        properties: {
          text: 'icon',
          fontSize: 10,
          fill: 'var(--interactive-accent)',
          textAlign: 'center',
        },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Icon',
      },
    ],
    exposedProps: [{ key: 'icon', label: 'Icon', type: 'text', defaultValue: 'icon' }],
    width: 32,
    height: 32,
    tags: ['button', 'toolbar', 'active'],
    isBuiltin: true,
    created_at: now,
    modified_at: now,
  },
];
