import type { ComponentDefinition } from '@/features/canvas/types';

const now = 0;

export const FEEDBACK_COMPONENTS: ComponentDefinition[] = [
  {
    id: 'builtin-feedback-toast',
    name: 'Toast',
    category: 'Feedback',
    icon: 'info',
    width: 300,
    height: 48,
    tags: ['feedback', 'toast', 'notification'],
    isBuiltin: true,
    exposedProps: [
      {
        key: 'message',
        label: 'Message',
        type: 'text',
        defaultValue: 'Action completed successfully.',
      },
    ],
    elements: [
      {
        id: 'bg',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 300,
        height: 48,
        rotation: 0,
        properties: {
          fill: 'var(--background-primary)',
          stroke: 'var(--border-color)',
          strokeWidth: 1,
          radius: 8,
          shadow: { x: 0, y: 4, blur: 12, spread: 0, color: 'rgba(0,0,0,0.1)' },
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Background',
      },
      {
        id: 'icon-area',
        element_type: 'circle',
        x: 12,
        y: 12,
        width: 24,
        height: 24,
        rotation: 0,
        properties: { fill: 'var(--interactive-accent)' },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Icon',
      },
      {
        id: 'msg',
        element_type: 'text',
        x: 44,
        y: 14,
        width: 240,
        height: 20,
        rotation: 0,
        properties: {
          text: 'Action completed successfully.',
          fontSize: 13,
          fill: 'var(--text-normal)',
          textAlign: 'left',
        },
        layer_id: 'default',
        z_index: 2,
        locked: false,
        visible: true,
        name: 'Message',
      },
    ],
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-feedback-alert',
    name: 'Alert Banner',
    category: 'Feedback',
    icon: 'alert-circle',
    width: 320,
    height: 56,
    tags: ['feedback', 'alert', 'banner', 'warning'],
    isBuiltin: true,
    exposedProps: [
      {
        key: 'message',
        label: 'Message',
        type: 'text',
        defaultValue: 'Please review the changes before continuing.',
      },
    ],
    elements: [
      {
        id: 'bg',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 320,
        height: 56,
        rotation: 0,
        properties: {
          fill: 'var(--background-primary)',
          stroke: 'var(--border-color)',
          strokeWidth: 1,
          radius: 8,
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Background',
      },
      {
        id: 'accent',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 4,
        height: 56,
        rotation: 0,
        properties: {
          fill: 'var(--text-warning)',
          borderRadius: { topLeft: 8, topRight: 0, bottomLeft: 8, bottomRight: 0 },
        },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Accent',
      },
      {
        id: 'title',
        element_type: 'text',
        x: 16,
        y: 10,
        width: 280,
        height: 18,
        rotation: 0,
        properties: {
          text: 'Warning',
          fontSize: 13,
          fontWeight: 600,
          fill: 'var(--text-warning)',
          textAlign: 'left',
        },
        layer_id: 'default',
        z_index: 2,
        locked: false,
        visible: true,
        name: 'Title',
      },
      {
        id: 'msg',
        element_type: 'text',
        x: 16,
        y: 30,
        width: 280,
        height: 18,
        rotation: 0,
        properties: {
          text: 'Please review the changes before continuing.',
          fontSize: 12,
          fill: 'var(--text-normal)',
          textAlign: 'left',
        },
        layer_id: 'default',
        z_index: 3,
        locked: false,
        visible: true,
        name: 'Message',
      },
    ],
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-feedback-progress',
    name: 'Progress Bar',
    category: 'Feedback',
    icon: 'activity',
    width: 240,
    height: 8,
    tags: ['feedback', 'progress', 'loading'],
    isBuiltin: true,
    exposedProps: [{ key: 'progress', label: 'Progress %', type: 'number', defaultValue: 60 }],
    elements: [
      {
        id: 'track',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 240,
        height: 8,
        rotation: 0,
        properties: { fill: 'var(--background-modifier-border)', radius: 4 },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Track',
      },
      {
        id: 'fill',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 144,
        height: 8,
        rotation: 0,
        properties: { fill: 'var(--interactive-accent)', radius: 4 },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Fill',
      },
    ],
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-feedback-spinner',
    name: 'Spinner',
    category: 'Feedback',
    icon: 'loader',
    width: 24,
    height: 24,
    tags: ['feedback', 'spinner', 'loading'],
    isBuiltin: true,
    exposedProps: [],
    elements: [
      {
        id: 'ring',
        element_type: 'circle',
        x: 0,
        y: 0,
        width: 24,
        height: 24,
        rotation: 0,
        properties: {
          fill: 'transparent',
          stroke: 'var(--background-modifier-border)',
          strokeWidth: 3,
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Track',
      },
      {
        id: 'arc',
        element_type: 'circle',
        x: 0,
        y: 0,
        width: 24,
        height: 24,
        rotation: 45,
        properties: { fill: 'transparent', stroke: 'var(--interactive-accent)', strokeWidth: 3 },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Active Arc',
      },
    ],
    created_at: now,
    modified_at: now,
  },
];
