import type { ComponentDefinition } from '@/features/canvas/types';

const now = 0;

function heading(
  id: string,
  name: string,
  size: number,
  weight: number,
  h: number
): ComponentDefinition {
  return {
    id,
    name,
    category: 'Typography',
    icon: 'type',
    width: 280,
    height: h,
    tags: ['typography', 'text', 'heading'],
    isBuiltin: true,
    exposedProps: [{ key: 'text', label: 'Text', type: 'text', defaultValue: name }],
    elements: [
      {
        id: 'text',
        element_type: 'text',
        x: 0,
        y: 0,
        width: 280,
        height: h,
        rotation: 0,
        properties: {
          text: name,
          fontSize: size,
          fontWeight: weight,
          fill: 'var(--text-primary)',
          textAlign: 'left',
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Text',
      },
    ],
    created_at: now,
    modified_at: now,
  };
}

export const TYPOGRAPHY_COMPONENTS: ComponentDefinition[] = [
  heading('builtin-typo-h1', 'Heading 1', 32, 700, 40),
  heading('builtin-typo-h2', 'Heading 2', 24, 600, 32),
  heading('builtin-typo-h3', 'Heading 3', 20, 600, 28),
  heading('builtin-typo-h4', 'Heading 4', 16, 600, 24),
  {
    id: 'builtin-typo-paragraph',
    name: 'Paragraph',
    category: 'Typography',
    icon: 'align-left',
    width: 280,
    height: 60,
    tags: ['typography', 'text', 'body'],
    isBuiltin: true,
    exposedProps: [
      {
        key: 'text',
        label: 'Text',
        type: 'text',
        defaultValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      },
    ],
    elements: [
      {
        id: 'text',
        element_type: 'text',
        x: 0,
        y: 0,
        width: 280,
        height: 60,
        rotation: 0,
        properties: {
          text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          fontSize: 14,
          lineHeight: 1.5,
          fill: 'var(--text-normal)',
          textAlign: 'left',
          verticalAlign: 'top',
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Paragraph',
      },
    ],
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-typo-label',
    name: 'Label',
    category: 'Typography',
    icon: 'tag',
    width: 80,
    height: 18,
    tags: ['typography', 'label', 'small'],
    isBuiltin: true,
    exposedProps: [{ key: 'text', label: 'Text', type: 'text', defaultValue: 'Label' }],
    elements: [
      {
        id: 'text',
        element_type: 'text',
        x: 0,
        y: 0,
        width: 80,
        height: 18,
        rotation: 0,
        properties: {
          text: 'Label',
          fontSize: 12,
          fontWeight: 500,
          fill: 'var(--text-muted)',
          textAlign: 'left',
          textTransform: 'uppercase',
          letterSpacing: 0.5,
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Label',
      },
    ],
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-typo-badge',
    name: 'Badge',
    category: 'Typography',
    icon: 'tag',
    width: 60,
    height: 24,
    tags: ['typography', 'badge', 'chip'],
    isBuiltin: true,
    exposedProps: [{ key: 'text', label: 'Text', type: 'text', defaultValue: 'Badge' }],
    elements: [
      {
        id: 'bg',
        element_type: 'rectangle',
        x: 0,
        y: 0,
        width: 60,
        height: 24,
        rotation: 0,
        properties: { fill: 'var(--interactive-accent)', radius: 12 },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Background',
      },
      {
        id: 'text',
        element_type: 'text',
        x: 8,
        y: 4,
        width: 44,
        height: 16,
        rotation: 0,
        properties: {
          text: 'Badge',
          fontSize: 11,
          fontWeight: 500,
          fill: 'var(--text-on-accent)',
          textAlign: 'center',
        },
        layer_id: 'default',
        z_index: 1,
        locked: false,
        visible: true,
        name: 'Text',
      },
    ],
    created_at: now,
    modified_at: now,
  },
  {
    id: 'builtin-typo-caption',
    name: 'Caption',
    category: 'Typography',
    icon: 'type',
    width: 200,
    height: 16,
    tags: ['typography', 'caption', 'small'],
    isBuiltin: true,
    exposedProps: [{ key: 'text', label: 'Text', type: 'text', defaultValue: 'Caption text' }],
    elements: [
      {
        id: 'text',
        element_type: 'text',
        x: 0,
        y: 0,
        width: 200,
        height: 16,
        rotation: 0,
        properties: {
          text: 'Caption text',
          fontSize: 11,
          fill: 'var(--text-faint)',
          textAlign: 'left',
        },
        layer_id: 'default',
        z_index: 0,
        locked: false,
        visible: true,
        name: 'Caption',
      },
    ],
    created_at: now,
    modified_at: now,
  },
];
