import type { SettingsEntry } from './settings-search';

export const SETTINGS_INDEX: SettingsEntry[] = [
  // ── General ───────────────────────────────────────────────────────
  {
    tab: 'general',
    section: 'Language',
    label: 'App Language',
    hint: 'More languages coming soon',
    id: 'app-language',
  },
  {
    tab: 'general',
    section: 'Startup',
    label: 'Homepage',
    hint: 'What to show when opening the vault',
    id: 'homepage-option',
  },
  {
    tab: 'general',
    section: 'Startup',
    label: 'Note path',
    hint: 'Relative path to the note',
    id: 'homepage-path',
  },
  {
    tab: 'general',
    section: 'Saving',
    label: 'Auto-save',
    hint: 'Automatically save notes after editing',
    id: 'auto-save',
  },
  {
    tab: 'general',
    section: 'Saving',
    label: 'Auto-save delay',
    hint: 'Milliseconds to wait before saving',
    id: 'auto-save-delay',
  },
  {
    tab: 'general',
    section: 'Saving',
    label: 'Confirm before delete',
    hint: 'Show confirmation dialog when deleting notes',
    id: 'confirm-delete',
  },
  {
    tab: 'general',
    section: 'Saving',
    label: 'New file name',
    hint: 'Default title for newly created notes',
    id: 'new-file-name',
  },
  {
    tab: 'general',
    section: 'Saving',
    label: 'Default note location',
    hint: 'Folder for new notes',
    id: 'default-note-loc',
  },
  {
    tab: 'general',
    section: 'Date & Time',
    label: 'Date format',
    hint: 'Date format string (date-fns)',
    id: 'date-format',
  },
  {
    tab: 'general',
    section: 'Date & Time',
    label: 'Time format',
    hint: '12h or 24h',
    id: 'time-format',
  },
  {
    tab: 'general',
    section: 'Updates',
    label: 'Check for updates on startup',
    hint: 'Silently checks for available updates',
    id: 'auto-updates',
  },
  {
    tab: 'general',
    section: 'Updates',
    label: 'Update channel',
    hint: 'Which releases to check for',
    id: 'update-channel',
  },
  {
    tab: 'general',
    section: 'Performance',
    label: 'Slow startup threshold',
    hint: 'Show a notification if startup takes longer',
    id: 'startup-threshold',
  },
  {
    tab: 'general',
    section: 'Performance',
    label: 'Lazy-load extensions',
    hint: 'Load editor extensions on demand for faster startup',
    id: 'lazy-ext',
  },

  // ── Editor ────────────────────────────────────────────────────────
  {
    tab: 'editor',
    section: 'Typography',
    label: 'Font Size',
    hint: 'Base font size for editor text',
    id: 'font-size',
  },
  {
    tab: 'editor',
    section: 'Typography',
    label: 'Line Height',
    hint: 'Spacing between lines of text',
    id: 'line-height',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Show line numbers',
    hint: 'Display line numbers in the editor gutter',
    id: 'line-numbers',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Fold gutter',
    hint: 'Show fold arrows in the gutter to collapse sections',
    id: 'fold-gutter',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Highlight active line',
    hint: 'Visually highlight the line the cursor is on',
    id: 'highlight-line',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Readable line length',
    hint: 'Constrain content to a maximum width for readability',
    id: 'readable-line',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Line width',
    hint: 'Maximum width in characters',
    id: 'line-width',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Frontmatter',
    hint: 'How YAML frontmatter is displayed in the editor',
    id: 'frontmatter-mode',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Word wrap',
    hint: 'Wrap long lines to fit the editor width',
    id: 'word-wrap',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Spell check',
    hint: 'Enable browser spell checking in the editor',
    id: 'spell-check',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Trim trailing whitespace',
    hint: 'Remove extra spaces at end of lines when saving',
    id: 'trim-ws',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Auto-close brackets',
    hint: 'Automatically close brackets and quotes',
    id: 'close-brackets',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Tab size',
    hint: 'Number of spaces per tab',
    id: 'tab-size',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Insert spaces',
    hint: 'Use spaces instead of tab characters',
    id: 'insert-spaces',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Hard line breaks',
    hint: 'Treat single newlines as hard line breaks in markdown',
    id: 'hard-breaks',
  },
  {
    tab: 'editor',
    section: 'Editor Behavior',
    label: 'Slash commands',
    hint: 'Press / outside the editor to open the command palette',
    id: 'slash-commands',
  },
  {
    tab: 'editor',
    section: 'View Mode',
    label: 'Enable live preview',
    hint: 'Allow live preview and reading modes',
    id: 'live-preview',
  },
  {
    tab: 'editor',
    section: 'View Mode',
    label: 'Default view mode',
    hint: 'View mode when opening a note',
    id: 'live-preview-mode',
  },
  {
    tab: 'editor',
    section: 'View Mode',
    label: 'Floating toolbar',
    hint: 'Show formatting toolbar above selected text',
    id: 'floating-toolbar',
  },
  {
    tab: 'editor',
    section: 'View Mode',
    label: 'Read-only mode',
    hint: 'Prevent editing note content',
    id: 'read-only',
  },
  {
    tab: 'editor',
    section: 'Speed Reader',
    label: 'Default WPM',
    hint: 'Words per minute when opening the speed reader',
    id: 'speed-wpm',
  },
  {
    tab: 'editor',
    section: 'Typewriter & Zen Mode',
    label: 'Typewriter mode',
    hint: 'Keep cursor centered vertically while typing',
    id: 'typewriter',
  },
  {
    tab: 'editor',
    section: 'Typewriter & Zen Mode',
    label: 'Typewriter offset',
    hint: 'Vertical position of the cursor',
    id: 'tw-offset',
  },
  {
    tab: 'editor',
    section: 'Typewriter & Zen Mode',
    label: 'Only on keyboard input',
    hint: "Don't scroll on mouse clicks",
    id: 'tw-keyboard',
  },
  {
    tab: 'editor',
    section: 'Typewriter & Zen Mode',
    label: 'Zen mode',
    hint: 'Dim non-focused text for distraction-free writing',
    id: 'zen-mode',
  },
  {
    tab: 'editor',
    section: 'Typewriter & Zen Mode',
    label: 'Visible lines',
    hint: 'Number of lines to keep un-dimmed',
    id: 'zen-lines',
  },
  {
    tab: 'editor',
    section: 'Typewriter & Zen Mode',
    label: 'Dim opacity',
    hint: 'How much to dim unfocused text',
    id: 'zen-opacity',
  },
  {
    tab: 'editor',
    section: 'Vim',
    label: 'Vim mode',
    hint: 'Enable vim keybindings in the editor',
    id: 'vim-mode',
  },
  {
    tab: 'editor',
    section: 'Vim',
    label: 'Show mode indicator',
    hint: 'Display current vim mode in the status bar',
    id: 'vim-show',
  },
  {
    tab: 'editor',
    section: 'Vim',
    label: 'Vimrc path',
    hint: 'Path to custom vimrc file',
    id: 'vimrc',
  },

  // ── Appearance ────────────────────────────────────────────────────
  {
    tab: 'appearance',
    section: 'Theme',
    label: 'Color scheme',
    hint: 'Light, dark, or follow system preference',
    id: 'theme-mode',
  },
  {
    tab: 'appearance',
    section: 'Theme',
    label: 'Custom theme',
    hint: 'Select a .css file from .bismuth/themes/',
    id: 'theme-path',
  },
  {
    tab: 'appearance',
    section: 'Theme',
    label: 'Accent color',
    hint: 'Primary color for buttons and highlights',
    id: 'accent-color',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'Show status bar',
    hint: 'Display status information at the bottom',
    id: 'status-bar',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'Compact mode',
    hint: 'Reduce spacing for more content on screen',
    id: 'compact-mode',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'Show sidebar icons',
    hint: 'Display icons in sidebar navigation',
    id: 'sidebar-icons',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'Native window frame',
    hint: 'Use system window decorations (restart required)',
    id: 'native-frame',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'Translucent window',
    hint: 'Semi-transparent window background (macOS only)',
    id: 'translucency',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'UI scale',
    hint: 'Scale all UI elements proportionally',
    id: 'ui-scale',
  },
  {
    tab: 'appearance',
    section: 'Interface',
    label: 'Interface font size',
    hint: 'Base size for menus, panels, and labels',
    id: 'if-size',
  },
  {
    tab: 'appearance',
    section: 'Fonts',
    label: 'Interface font',
    hint: 'Font used for menus, buttons, and labels',
    id: 'font-interface',
  },
  {
    tab: 'appearance',
    section: 'Fonts',
    label: 'Text font',
    hint: 'Font used for note content',
    id: 'font-text',
  },
  {
    tab: 'appearance',
    section: 'Fonts',
    label: 'Monospace font',
    hint: 'Font used for code blocks and inline code',
    id: 'font-mono',
  },

  // ── Vault & Git ───────────────────────────────────────────────────
  {
    tab: 'vault',
    section: 'Version Control',
    label: 'Enable Git integration',
    hint: 'Track changes with Git',
    id: 'sv-enable-git',
  },
  {
    tab: 'vault',
    section: 'Version Control',
    label: 'Auto-commit changes',
    hint: 'Automatically commit after saving',
    id: 'sv-auto-commit',
  },
  {
    tab: 'vault',
    section: 'Version Control',
    label: 'Sync on startup',
    hint: 'Pull latest changes when opening vault',
    id: 'sv-sync-startup',
  },
  {
    tab: 'vault',
    section: 'Version Control',
    label: 'Commit message template',
    hint: 'Use [filename] as placeholder',
    id: 'sv-commit-tpl',
  },
  {
    tab: 'vault',
    section: 'Backups',
    label: 'Enable automatic backups',
    hint: 'Periodically back up vault data',
    id: 'sv-backups',
  },
  {
    tab: 'vault',
    section: 'Versioning',
    label: 'Enable note versioning',
    hint: 'Keep historical snapshots of notes',
    id: 'sv-versioning',
  },
  {
    tab: 'vault',
    section: 'Versioning',
    label: 'Retention count',
    hint: 'Max versions kept per note',
    id: 'sv-retention',
  },
  {
    tab: 'vault',
    section: 'Versioning',
    label: 'LLM classify changes',
    hint: 'Use AI to label version diffs',
    id: 'sv-llm-classify',
  },
  {
    tab: 'vault',
    section: 'Changelog',
    label: 'Auto-update changelog',
    hint: 'Log edits to a changelog file',
    id: 'sv-changelog',
  },
  {
    tab: 'vault',
    section: 'Changelog',
    label: 'Changelog path',
    hint: 'Relative path inside vault',
    id: 'sv-clog-path',
  },
  {
    tab: 'vault',
    section: 'Changelog',
    label: 'Use wikilinks',
    hint: 'Link note names as [[wikilinks]]',
    id: 'sv-clog-wiki',
  },
  {
    tab: 'vault',
    section: 'Changelog',
    label: 'Max recent files',
    hint: 'Entries shown in changelog',
    id: 'sv-clog-max',
  },

  // ── Calendar ──────────────────────────────────────────────────────
  {
    tab: 'calendar',
    section: 'View',
    label: 'Default View',
    hint: 'Calendar view shown on launch',
    id: 'cal-default-view',
  },
  {
    tab: 'calendar',
    section: 'View',
    label: 'Week starts on',
    hint: 'First day of the week',
    id: 'cal-week-start',
  },
  {
    tab: 'calendar',
    section: 'View',
    label: 'Default event duration',
    hint: 'Duration in minutes for new events',
    id: 'cal-duration',
  },
  {
    tab: 'calendar',
    section: 'View',
    label: 'Show completed events',
    hint: 'Display completed events in calendar views',
    id: 'cal-show-completed',
  },
  {
    tab: 'calendar',
    section: 'View',
    label: 'Time slot height',
    hint: 'Pixel height of each hour slot',
    id: 'cal-slot-height',
  },
  {
    tab: 'calendar',
    section: 'Notes',
    label: 'Show note blurbs',
    hint: 'Display description previews on event chips in day view',
    id: 'cal-blurbs',
  },
  {
    tab: 'calendar',
    section: 'Notes',
    label: 'Event note folder',
    hint: 'Default folder for notes created from events',
    id: 'cal-note-folder',
  },

  // ── Canvas ────────────────────────────────────────────────────────
  {
    tab: 'canvas',
    section: 'Grid',
    label: 'Show grid',
    hint: 'Display grid lines on the canvas',
    id: 'canvas-grid',
  },
  {
    tab: 'canvas',
    section: 'Grid',
    label: 'Grid size',
    hint: 'Spacing between grid lines in pixels',
    id: 'canvas-grid-size',
  },
  {
    tab: 'canvas',
    section: 'Grid',
    label: 'Snap to grid',
    hint: 'Snap elements to grid when moving',
    id: 'canvas-snap',
  },
  {
    tab: 'canvas',
    section: 'View',
    label: 'Default zoom',
    hint: 'Initial zoom level when opening canvas',
    id: 'canvas-zoom',
  },
  {
    tab: 'canvas',
    section: 'View',
    label: 'Show minimap',
    hint: 'Display a minimap overview of the canvas',
    id: 'canvas-minimap',
  },

  // ── AI ────────────────────────────────────────────────────────────
  {
    tab: 'ai',
    section: 'AI Assistant',
    label: 'Enable AI',
    hint: 'Enable AI-powered features',
    id: 'llm-enabled',
  },
  {
    tab: 'ai',
    section: 'AI Assistant',
    label: 'Provider',
    hint: 'AI service provider',
    id: 'llm-provider',
  },
  {
    tab: 'ai',
    section: 'AI Assistant',
    label: 'API key',
    hint: 'Authentication key for the provider',
    id: 'llm-api-key',
  },
  {
    tab: 'ai',
    section: 'AI Assistant',
    label: 'API URL',
    hint: 'Base URL for the API endpoint',
    id: 'llm-api-url',
  },
  {
    tab: 'ai',
    section: 'AI Assistant',
    label: 'Model',
    hint: 'Model identifier to use',
    id: 'llm-model',
  },
  {
    tab: 'ai',
    section: 'AI Assistant',
    label: 'Max history',
    hint: 'Number of messages to keep in conversation',
    id: 'llm-history',
  },
  {
    tab: 'ai',
    section: 'OCR',
    label: 'Enable OCR',
    hint: 'Extract text from images',
    id: 'ocr-enabled',
  },
  {
    tab: 'ai',
    section: 'OCR',
    label: 'Default language',
    hint: 'Primary language for OCR',
    id: 'ocr-lang',
  },
  {
    tab: 'ai',
    section: 'OCR',
    label: 'OCR model path',
    hint: 'Path to local Tesseract/OCR model',
    id: 'ocr-model',
  },
  {
    tab: 'ai',
    section: 'OCR',
    label: 'Amharic model path',
    hint: 'Path to Amharic-specific OCR model',
    id: 'ocr-amharic',
  },
  {
    tab: 'ai',
    section: 'Media',
    label: 'Ambient sounds',
    hint: 'Play background sounds while writing',
    id: 'music-enabled',
  },
  {
    tab: 'ai',
    section: 'Media',
    label: 'Voice format',
    hint: 'Recording format for voice notes',
    id: 'voice-format',
  },
  {
    tab: 'ai',
    section: 'Media',
    label: 'Voice quality',
    hint: 'Audio recording quality',
    id: 'voice-quality',
  },

  // ── Knowledge ─────────────────────────────────────────────────
  {
    tab: 'knowledge',
    section: 'Topic Linking',
    label: 'Enable topic linking',
    hint: 'Detect unlinked mentions of note titles',
    id: 'kn-topic-enabled',
  },
  {
    tab: 'knowledge',
    section: 'Topic Linking',
    label: 'Minimum title length',
    hint: 'Shortest title to match (characters)',
    id: 'kn-topic-min-len',
  },
  {
    tab: 'knowledge',
    section: 'Topic Linking',
    label: 'Case-sensitive matching',
    hint: 'Require exact case when detecting mentions',
    id: 'kn-topic-case',
  },
  {
    tab: 'knowledge',
    section: 'Writing',
    label: 'Daily word goal',
    hint: 'Target word count per day',
    id: 'kn-writing-goal',
  },
  {
    tab: 'knowledge',
    section: 'Writing',
    label: 'Sprint duration',
    hint: 'Minutes per writing sprint',
    id: 'kn-writing-sprint',
  },
  {
    tab: 'knowledge',
    section: 'Writing',
    label: 'Auto-save during writing',
    hint: 'Save automatically while in a writing session',
    id: 'kn-writing-autosave',
  },

  // ── Gamification ──────────────────────────────────────────────
  {
    tab: 'gamification',
    section: 'XP & Levels',
    label: 'Enable gamification',
    hint: 'Track XP, levels, and streaks',
    id: 'gm-enabled',
  },
  {
    tab: 'gamification',
    section: 'XP & Levels',
    label: 'Show XP notifications',
    hint: 'Display toast when earning XP',
    id: 'gm-xp-notify',
  },
  {
    tab: 'gamification',
    section: 'Streaks',
    label: 'Show streak reminders',
    hint: 'Remind you to maintain your daily streak',
    id: 'gm-streak-remind',
  },

  // ── Integration ───────────────────────────────────────────────────
  {
    tab: 'integration',
    section: 'Flashcards',
    label: 'Enable flashcards',
    hint: 'Extract flashcards from notes',
    id: 'int-flashcards',
  },
  {
    tab: 'integration',
    section: 'Flashcards',
    label: 'Auto-scan notes',
    hint: 'Automatically detect flashcard syntax',
    id: 'int-auto-scan',
  },
  {
    tab: 'integration',
    section: 'Flashcards',
    label: 'Anki Connect port',
    hint: 'Port for Anki Connect plugin',
    id: 'int-anki-port',
  },
  {
    tab: 'integration',
    section: 'Flashcards',
    label: 'Deck prefix',
    hint: 'Prefix for exported Anki decks',
    id: 'int-deck-prefix',
  },

  // ── Window ────────────────────────────────────────────────────────
  {
    tab: 'window',
    section: 'Window Behavior',
    label: 'Start in fullscreen',
    hint: 'Automatically enter fullscreen mode when the app launches',
    id: 'start-fullscreen',
  },
  {
    tab: 'window',
    section: 'Window Behavior',
    label: 'Restore window size',
    hint: 'Remember the window size from the last session',
    id: 'restore-size',
  },
  {
    tab: 'window',
    section: 'Window Behavior',
    label: 'Restore window position',
    hint: 'Remember the window position from the last session',
    id: 'restore-position',
  },
  {
    tab: 'window',
    section: 'System Tray',
    label: 'Close to tray',
    hint: 'Keep the app running in the system tray when the window is closed',
    id: 'close-to-tray',
  },
  {
    tab: 'window',
    section: 'System Tray',
    label: 'Minimize to tray',
    hint: 'Move the app to the system tray when minimized instead of the dock',
    id: 'minimize-to-tray',
  },
];
