/**
 * Centralized icon registry mapping semantic names to Lucide components.
 * All icons sourced from @lucide/svelte — one import, tree-shakeable.
 */
import {
  Activity,
  AlignHorizontalDistributeCenter,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignVerticalDistributeCenter,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  ArrowUp,
  Ban,
  Bold,
  BookCopy,
  Bookmark,
  BookOpen,
  Box,
  CalendarDays,
  CalendarPlus,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CirclePlus,
  ClipboardList,
  Clock,
  CloudUpload,
  Code,
  CodeXml,
  Command,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  File,
  FileStack,
  FileText,
  Film,
  Folder,
  FolderKanban,
  FolderOpen,
  GitBranch,
  Globe,
  GraduationCap,
  Hand,
  Hash,
  Heading,
  Heart,
  Highlighter,
  House,
  Image,
  Inbox,
  Info,
  Italic,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2,
  List,
  ListOrdered,
  ListTodo,
  Lock,
  LockOpen,
  MessageSquare,
  MessageSquareQuote,
  Mic,
  Minus,
  Monitor,
  MonitorPlay,
  MousePointer2,
  Music,
  Network,
  Paintbrush,
  Palette,
  Paperclip,
  Pause,
  PenLine,
  PenTool,
  Play,
  Plus,
  Quote,
  Redo2,
  RefreshCw,
  Rss,
  Scissors,
  Scroll,
  Search,
  Settings,
  ShieldCheck,
  Shuffle,
  Slash,
  Sparkles,
  Spline,
  Sprout,
  Square,
  SquarePen,
  StickyNote,
  Strikethrough,
  Table,
  Tag,
  TextAlignStart,
  Timer,
  Trash2,
  Trophy,
  Type,
  Underline,
  Undo2,
  Upload,
  User,
  X,
  Zap,
} from '@lucide/svelte';
import type { Component } from 'svelte';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyComponent = Component<any>;

export const ICON_COMPONENTS: Record<string, AnyComponent> = {
  // ── Hubs ──────────────────────────────────────────────────────────
  home: House,
  navigator: House,
  editor: SquarePen,
  planner: CalendarDays,
  knowledge: BookOpen,
  canvas: LayoutGrid,

  // ── Navigator panels ──────────────────────────────────────────────
  files: FolderOpen,
  search: Search,
  recent: Clock,
  bookmarks: Bookmark,

  // ── Editor panels ─────────────────────────────────────────────────
  outline: ListTodo,
  properties: ClipboardList,
  links: Link,
  backlinks: Link2,
  outgoing: ExternalLink,
  wordcount: FileText,
  versions: Clock,
  footnotes: MessageSquare,
  symbols: Hash,
  lint: ShieldCheck,
  speedreader: FastForward,

  // ── Planner panels ────────────────────────────────────────────────
  calendar: CalendarDays,
  tasks: ListTodo,
  daily: CalendarPlus,
  periodic: RefreshCw,
  habits: ShieldCheck,
  projects: FolderKanban,

  // ── Knowledge panels ──────────────────────────────────────────────
  tags: Tag,
  graph: Network,
  citations: MessageSquareQuote,
  flashcards: BookCopy,
  connections: Sparkles,

  // ── Canvas panels ─────────────────────────────────────────────────
  layers: Layers,
  elements: LayoutDashboard,

  // ── Integration panels ────────────────────────────────────────────
  integration: Zap,
  git: GitBranch,
  ai: Sparkles,
  backup: CloudUpload,
  publish: Globe,
  rss: Rss,
  import: Download,
  importer: Upload,
  clipper: Scissors,
  annotator: StickyNote,

  // ── Features ──────────────────────────────────────────────────────
  pokemon: Zap,
  templates: FileStack,
  capture: CirclePlus,
  creative: Paintbrush,
  ideas: Sparkles,
  media: Image,
  'media-browser': MonitorPlay,
  gallery: LayoutGrid,
  wellness: Heart,
  mood: Heart,
  journal: BookOpen,
  writing: PenLine,
  study: GraduationCap,
  voice: Mic,
  embed: Link,
  attachments: Paperclip,
  timekeep: Timer,
  longform: Scroll,
  storyteller: PenTool,
  trophy: Trophy,
  'vault-stats': ChartColumn,

  // ── Common UI ─────────────────────────────────────────────────────
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  plus: Plus,
  close: X,
  trash: Trash2,
  unresolved: Ban,
  folderOpen: FolderOpen,
  folder: Folder,
  document: FileText,
  documentBlank: File,
  bookOpen: BookOpen,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  lockOpen: LockOpen,
  check: Check,
  photo: Image,
  musicalNote: Music,
  film: Film,
  paperclip: Paperclip,
  cube: Box,
  inbox: Inbox,
  textBars: TextAlignStart,
  externalLink: ExternalLink,
  'arrow-up': ArrowUp,
  refresh: RefreshCw,
  play: Play,
  pause: Pause,
  grid: LayoutGrid,
  list: List,
  image: Image,
  music: Music,
  video: Film,
  fileText: FileText,
  x: X,
  shield: ShieldCheck,
  checkCircle: CircleCheck,
  hash: Hash,
  user: User,

  // ── Editor formatting ─────────────────────────────────────────────
  heading: Heading,
  caretDown: ChevronDown,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  highlightPen: Highlighter,
  codeInline: Code,
  listBullet: List,
  listNumbered: ListOrdered,
  blockquote: Quote,
  hr: Minus,
  codeBlock: CodeXml,
  table: Table,

  // ── Settings tabs ─────────────────────────────────────────────────
  activity: Activity,
  settings: Settings,
  help: Info,
  command: Command,
  info: Info,
  palette: Palette,
  window: Monitor,
  sparkles: Sparkles,
  shuffle: Shuffle,
  chainLink: Link2,
  edit: SquarePen,

  // ── Canvas tools ──────────────────────────────────────────────────
  'tool-select': MousePointer2,
  'tool-rect': Square,
  'tool-ellipse': Circle,
  'tool-line': Slash,
  'tool-text': Type,
  'tool-note': StickyNote,
  'tool-connect': Spline,
  'tool-pan': Hand,
  undo: Undo2,
  redo: Redo2,

  // ── Canvas alignment ──────────────────────────────────────────────
  'align-left': AlignHorizontalJustifyStart,
  'align-center-x': AlignHorizontalJustifyCenter,
  'align-right': AlignHorizontalJustifyEnd,
  'align-top': AlignVerticalJustifyStart,
  'align-center-y': AlignVerticalJustifyCenter,
  'align-bottom': AlignVerticalJustifyEnd,
  'distribute-h': AlignHorizontalDistributeCenter,
  'distribute-v': AlignVerticalDistributeCenter,

  // ── Shapes / canvas elements ──────────────────────────────────────
  rect: Square,
  ellipse: Circle,
  line: Slash,

  // ── Vault templates ───────────────────────────────────────────────
  'tmpl-para': LayoutGrid,
  'tmpl-decimal': ListOrdered,
  'tmpl-zettelkasten': Link2,
  'tmpl-academic': GraduationCap,
  'tmpl-garden': Sprout,
  'tmpl-second-brain': Sparkles,
  'tmpl-developer': CodeXml,
  'tmpl-moc': Network,
};
